author:
  name: Aaron Delani
  url: http://aarondelani.com

input: GFM
hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem


# Syntax highlighting
highlighter: rouge

# Setup
title: Aaron Delani
tagline: Everything is Under Construction
url: http://aarondelani.github.io/

baseurl: ""

permalink: /blog/:year/:month/:day/:title
paginate: 5


# Assets

sass:
sass_dir: css
style: compressed

exclude: [node_modules, config.rb, Gemfile, Gemfile.lock, gulpfile.js, README.md]
