name: Aaron Delani

input: GFM
hard_wrap: false
gems:
   - jekyll-coffeescript
#   - jekyll-paginate
permalink: /blog/:year/:month/:day/:title
# sass:
#   sass_dir: css
#   style: compressed

# Syntax highlighting
highlighter:         pygments


# Setup
title:               Aaron Delani
tagline:             Testing Site
url:                 http://aarondelani.github.io/
baseurl:             /aarondelani.github.io/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
