name: Aaron Delani

input: GFM
hard_wrap: false
gems:
   - jekyll-coffeescript
#   - jekyll-paginate
permalink: /blog/:year/:month/:day/:title
# sass:
#   sass_dir: css
#   style: compressed

# Syntax highlighting
highlighter: rouge

# Setup
title: Aaron Delani
tagline: Everything is Under Construction
url: http://aarondelani.github.io/
# baseurl:

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          css
  style:            :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude: [node_modules, config.rb, Gemfile, Gemfile.lock, gulpfile.js, README.md]
